AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Parameters:
DBName:
  AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  Default: wordpressdb
  Description: The wordpress database name
  MaxLength: '64'
  MinLength:'1'
  Type: String
DbPassword:
  AllowedPattern: '[a-zA-Z0-9]*'
  ConstraintDescription: must contain only a alphanumeric characters.
  Description: The wordpress database admin account password
  MaxLength: '60'
  MinLength: '9'
  NoEcho: 'true'
  Type: String
DBRootPassword:
  AllowedPattern: '[a-zA-Z0-9]*'
  ConstraintDescription: must contain only alphanumeric characters.
  Description: MySQL root password
  MaxLength: '41'
  MinLength: '9'
  NoEcho: 'true'
  Type: String
DBUser:
   AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
   ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
   Description: The WordPress database admin account username
   MaxLength: '16'
   MinLength: '1'
   NoEcho: 'true'
   Type: String
InstanceType:
  AllowedValues: t2.micro
  ConstraintDescription: must be a valid EC2 instance type.
  Default: t2.micro
  Description: webserver ec2 instance type.
  Type: String
KeyName:
  ConstraintDescription: must be the name of an existing EC2 KeyPair.
  Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
  Type: AWS::EC2::KeyPair::KeyName
SSHLocation:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Default: 0.0.0.0/0
    Description: The IP address range that can be used to SSH to the EC2 instances
    MaxLength: '18'
    MinLength: '9'
    Type: String  
Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64
AWSRegionArch2AMI:
  eu-west-1:
      HVM64: ami-bff32ccc
      HVMG2: ami-83fd23f0
      PV64: ami-95e33ce6
Resources:
WebServer:
  Type: AWS::EC2::Instance
  
  

